network:
  map:
    testnet:
        max-node-number: 10
        min-node-number: 2
        lease-days: 5
    ffweimar:
        max-node-number: 1000
        min-node-number: 2
        lease-days: 30
spring:
    jackson:
        serialization:
            indent_output: true
    messages:
        basename: i18n/messages
        cache-seconds: -1
        encoding: UTF-8
stage: testing
